spring.application.name=auth-service

# =========================
# === Database Settings ===
# =========================
spring.datasource.url=jdbc:mariadb://localhost:3306/registry
spring.datasource.username=root
spring.datasource.password=swapnil@92
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# =========================
# === JPA & Hibernate ===
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# JWT Configuration
jwt.secret.key=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

# =========================
# === Spring Mail Config ===
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=w851843@gmail.com
spring.mail.password=wzsijhtmqkdmwtbz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
